language: python

sudo: false

cache:
  apt: true
  directories:
  - ${HOME}/.smt_solvers/btor
  - ${HOME}/.smt_solvers/bdd
  - ${HOME}/.cache/pip
  - ${HOME}/python_bindings/all
  - ${HOME}/python_bindings/msat
  - ${HOME}/python_bindings/z3
  - ${HOME}/python_bindings/cvc4
  - ${HOME}/python_bindings/yices
  - ${HOME}/python_bindings/bdd
  - ${HOME}/python_bindings/picosat
  - ${HOME}/python_bindings/btor

addons:
  apt:
    packages:
    - python-setuptools
    - python-nose
    - python-pip
    - python-dev
    - make
    - build-essential
    - swig
    - libgmp-dev
    - autoconf
    - libtool
    - wget
    - curl
    - libboost-dev
    - python3-all-dev

python:
  - 2.7
  - 3.5
  - pypy


# Multiple envs will cause multiple build across multiple python versions.
# We test the following:
# 1. PySMT w/o solvers
# 2. PySMT with one solver at the time
#
env:
  matrix:
    - PYSMT_SOLVER="all"
    - PYSMT_SOLVER="None"
    - PYSMT_SOLVER="msat"
    - PYSMT_SOLVER="z3"
    - PYSMT_SOLVER="cvc4"
    - PYSMT_SOLVER="yices"
    - PYSMT_SOLVER="bdd"
    - PYSMT_SOLVER="picosat"
    - PYSMT_SOLVER="btor"
    - PYSMT_SOLVER="msat_wrap"
    - PYSMT_SOLVER="z3_wrap"

matrix:
  fast_finish: true

  exclude:
    - python: pypy
      env: PYSMT_SOLVER="msat"
    - python: pypy
      env: PYSMT_SOLVER="z3"
    - python: pypy
      env: PYSMT_SOLVER="cvc4"
    - python: pypy
      env: PYSMT_SOLVER="yices"
    - python: pypy
      env: PYSMT_SOLVER="bdd"
    - python: pypy
      env: PYSMT_SOLVER="picosat"
    - python: pypy
      env: PYSMT_SOLVER="btor"
    - python: pypy
      env: PYSMT_SOLVER="all"

install:
  # This is for btor that fails to find the python 3 library to link
  - "export LIBRARY_PATH=${LIBRARY_PATH}:/opt/python/3.4.2/lib"
  - "export LIBRARY_PATH=${LIBRARY_PATH}:/opt/python/3.5.2/lib"
  # For some reason, Travis CI cannot find the command python3.5-config.
  # Therefore, we force the path here
  - if [ "${TRAVIS_PYTHON_VERSION}" == "3.5" ]; then export PATH=${PATH}:/opt/python/3.5.2/bin/ ; fi
  - "pip install python-coveralls"
  - "pip install six"
  - if [ "${PYSMT_SOLVER}" == "all" ] || [ "${PYSMT_SOLVER}" == "btor" ]; then pip install cython; fi
  - "export BINDINGS_FOLDER=${HOME}/python_bindings/${PYSMT_SOLVER}"
  - "mkdir -p ${BINDINGS_FOLDER}"
  - "python install.py --confirm-agreement --bindings-path ${BINDINGS_FOLDER}"
  - "eval `python install.py --env --bindings-path ${BINDINGS_FOLDER}`"
  - if [ "${PYSMT_SOLVER}" == "all" ] || [ "${PYSMT_SOLVER}" == "z3_wrap" ]; then python install.py --z3 --conf --force; cp -v $(find ~/.smt_solvers/ -name z3 -type f) pysmt/test/smtlib/bin/z3; chmod +x pysmt/test/smtlib/bin/z3; mv pysmt/test/smtlib/bin/z3.solver.sh.template pysmt/test/smtlib/bin/z3.solver.sh ; fi
  - if [ "${PYSMT_SOLVER}" == "all" ] || [ "${PYSMT_SOLVER}" == "msat_wrap" ]; then python install.py --msat --conf --force; cp -v $(find ~/.smt_solvers/ -name mathsat -type f) pysmt/test/smtlib/bin/mathsat; mv pysmt/test/smtlib/bin/mathsat.solver.sh.template pysmt/test/smtlib/bin/mathsat.solver.sh ; fi

script:
  - "echo ${PYTHONPATH}"
  - "python install.py --check"
  - "nosetests pysmt -v"
  - if [ "${PYSMT_SOLVER}" == "all" ]; then python install.py --msat --conf --force; cp -v $(find ~/.smt_solvers/ -name mathsat -type f) /tmp/mathsat; (for ex in `ls examples/*.py`; do echo $ex; python $ex || exit $?; done); fi

after_succes:
  - coveralls
